version: 0.0
os: linux
files:
  - source: /.
    destination: /var/www/html/
permissions:
   - object: scripts/rubystuff
     mode: 644
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 10
      runas:
 
   

